import { Suspense, useEffect, useState } from 'react';
import { Canvas } from '@react-three/fiber';
import TechOrb from './TechOrb';
import ParticleField from './ParticleField';
import SceneLighting from './SceneLighting';
import WebGLFallback from './WebGLFallback';
function useSceneSettings() { const [settings, setSettings] = useState({ supported: true, reducedMotion: false, compact: false, lowPower: false, visible: true }); useEffect(() => { const motion = matchMedia('(prefers-reduced-motion: reduce)'); const update = () => { const compact = window.innerWidth < 700; const lowPower = compact || (navigator.deviceMemory && navigator.deviceMemory <= 4) || (navigator.hardwareConcurrency && navigator.hardwareConcurrency <= 4); setSettings({ supported: Boolean(window.WebGLRenderingContext), reducedMotion: motion.matches, compact, lowPower, visible: !document.hidden }); }; const visibility = () => setSettings((current) => ({ ...current, visible: !document.hidden })); update(); window.addEventListener('resize', update, { passive: true }); document.addEventListener('visibilitychange', visibility); motion.addEventListener('change', update); return () => { window.removeEventListener('resize', update); document.removeEventListener('visibilitychange', visibility); motion.removeEventListener('change', update); }; }, []); return settings; }
function HeroWorld({ reducedMotion, compact, lowPower }) { return <><perspectiveCamera makeDefault position={[0, 0, compact ? 6.8 : 6.15]} fov={compact ? 45 : 41} /><SceneLighting reducedMotion={reducedMotion || lowPower} /><TechOrb reducedMotion={reducedMotion || lowPower} />{!reducedMotion && <ParticleField count={lowPower ? 20 : compact ? 28 : 64} />}</>; }
export default function HeroScene() { const { supported, reducedMotion, compact, lowPower, visible } = useSceneSettings(); if (!supported) return <WebGLFallback />; const frameLoop = !visible ? 'never' : reducedMotion ? 'demand' : 'always'; return <Canvas dpr={[1, compact ? 1.1 : 1.5]} frameloop={frameLoop} gl={{ antialias: false, alpha: true, powerPreference: 'high-performance' }} camera={{ position: [0, 0, compact ? 6.8 : 6.15], fov: compact ? 45 : 41 }}><Suspense fallback={null}><HeroWorld reducedMotion={reducedMotion} compact={compact} lowPower={lowPower} /></Suspense></Canvas>; }
