import { lazy, Suspense, useEffect, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, CircleDot, Code2, MoveUpRight, Quote, Send, Sparkles } from 'lucide-react';
import Navbar from './components/navigation/Navbar';
import ContactForm from './components/sections/ContactForm';
import { process, principles, projects, services, technologies } from './data/content';
const HeroScene=lazy(()=>import('./components/3d/HeroScene'));
const Section=({id,eyebrow,title,children,className=''})=><section id={id} className={`section ${className}`}><div className="section-head"><p className="eyebrow">{eyebrow}</p>{title&&<h2>{title}</h2>}</div>{children}</section>;
function App(){const[theme,setTheme]=useState(()=>localStorage.getItem('theme')|| (matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'));useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('theme',theme)},[theme]);return <><Navbar theme={theme} setTheme={setTheme}/><main>
<section className="hero" id="home"><div className="hero-copy"><p className="eyebrow hero-eyebrow"><i/> Digital products, deliberately built</p><h1>Technology that turns ambitious ideas into <em>powerful</em> digital products.</h1><p className="hero-text">MercuReal Tech Solutions builds modern websites, intelligent software, AI-powered solutions, automation systems, and digital experiences designed to move businesses forward.</p><div className="hero-actions"><a href="#contact" className="button">Start a Project <ArrowUpRight size={17}/></a><a href="#projects" className="button button-ghost">Explore Our Work <ArrowDownRight size={17}/></a></div><div className="hero-notes"><span><Check size={14}/> Human-centered</span><span><Check size={14}/> Built to last</span><span><Check size={14}/> AI-aware</span></div></div><div className="hero-visual" aria-label="Interactive abstract technology structure"><div className="scene-label"><span>01 / INTELLIGENCE CORE</span><b>Live system</b></div><Suspense fallback={<div className="webgl-fallback"><span>◌</span></div>}><HeroScene/></Suspense><div className="scene-orbit">CONNECTED<br/>BY DESIGN</div></div></section>
<section className="trust-strip" aria-label="Technology capabilities"><p>Thoughtful digital work across</p><div><span>PRODUCT</span><span>ENGINEERING</span><span>AI</span><span>AUTOMATION</span><span>DESIGN</span></div></section>
<Section id="services" eyebrow="01 / SERVICES" title={<>Built for ideas that deserve more than a template.</>}><div className="service-grid">{services.map(({icon:Icon,title,text},index)=><article className="service-card" key={title}><span className="card-number">0{index+1}</span><Icon size={25}/><h3>{title}</h3><p>{text}</p><a href="#contact" aria-label={`Discuss ${title}`}>Explore <ChevronRight size={16}/></a></article>)}</div></Section>
<Section id="about" eyebrow="02 / OUR APPROACH" title={<>Engineering clarity into every <em>useful</em> detail.</>} className="about"><div className="about-layout"><div><p className="large-copy">MercuReal brings engineering, design, AI, automation, and modern web technology into one considered product practice.</p><p>We work from the inside out: understand the real problem, build the right system, then make every interaction feel clear and capable.</p><a href="#contact" className="text-button">Talk about your idea <ArrowUpRight size={16}/></a></div><div className="signal-card"><span className="eyebrow">THE WORKING SIGNAL</span><div className="signal"><i/><i/><i/><i/><i/><i/><i/><i/></div><p>Complexity is a material. We shape it into something teams and customers can actually use.</p><div className="signal-footer"><span>DESIGN</span><MoveUpRight size={18}/><span>DELIVERY</span></div></div></div></Section>
<Section id="solutions" eyebrow="03 / CAPABILITIES" title="The tools are familiar. The way they work together is the point."><div className="tech-grid">{technologies.map(([name,Icon])=><div className="tech-chip" key={name}><Icon size={19}/><span>{name}</span><b>+</b></div>)}</div></Section>
<Section id="projects" eyebrow="04 / SELECTED CONCEPTS" title="Product ideas, visualized with intent."><p className="section-intro">A collection of fictional concept work. These are showcases of capability, not client claims.</p><div className="project-grid">{projects.map((project,index)=><article className={`project-card ${project.tone}`} key={project.name}><div className="project-art"><span className="project-index">0{index+1}</span><div className="ui-window"><i/><i/><i/><b/><b/><b/></div></div><div className="project-copy"><p>{project.category}</p><h3>{project.name}</h3><span>{project.text}</span><div>{project.tags.map(tag=><small key={tag}>{tag}</small>)}</div></div></article>)}</div></Section>
<Section id="process" eyebrow="05 / PROCESS" title="A clear path from first question to launch day."><div className="process-list">{process.map((step,index)=><article key={step}><span>0{index+1}</span><i/><h3>{step}</h3><p>{['Understand the landscape and define the opportunity.','Set direction, constraints, and the success measures.','Shape the experience, system, and visual language.','Develop in focused, visible iterations.','Check the details that make the work dependable.','Release with a foundation for what comes next.'][index]}</p></article>)}</div></Section>
<Section id="why" eyebrow="06 / WHY MERCUREAL" title="Ambition needs a partner with practical range."><div className="principle-grid">{principles.map(([title,text])=><article key={title}><CircleDot size={18}/><h3>{title}</h3><p>{text}</p></article>)}</div></Section>
<Section id="testimonials" eyebrow="07 / TESTIMONIALS" title="The space for future partnerships."><div className="testimonial"><Quote size={38}/><div><p>Genuine client perspectives belong here. This flexible component is intentionally prepared for future testimonials, with no invented endorsements.</p><span>— MercuReal testimonial area</span></div></div></Section>
<section className="cta"><Sparkles size={21}/><p className="eyebrow">MAKE THE NEXT MOVE</p><h2>Have an idea with <em>momentum?</em></h2><a href="#contact" className="button button-light">Start a Project <ArrowUpRight size={17}/></a></section>
<Section id="contact" eyebrow="08 / CONTACT" title="Tell us what you’re trying to make better."><div className="contact-layout"><div><p className="large-copy">The brief can be rough. A useful first conversation rarely is.</p><p>Share the challenge, the outcome you want, or simply the thought that keeps returning. We’ll start there.</p><a className="contact-email" href="mailto:hello@mercureal.tech">hello@mercureal.tech <Send size={16}/></a></div><ContactForm/></div></Section>
</main><footer><a className="brand" href="#home"><span className="brand-mark">M</span><span>MercuReal <em>Tech Solutions</em></span></a><p>Digital products with intelligence and intention.</p><span>© {new Date().getFullYear()} MercuReal Tech Solutions</span></footer></>}
export default App;
